version: '3'
services:
  app:
    container_name: race-condition-mongo-test
    restart: always
    build: .
    ports:
      - '5500:3000'
    depends_on:
      - mongo

  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - '27017:27017'

  mongo-express:
    container_name: mongo-express
    image: mongo-express
    ports:
      - '8083:8081'